language: go

go:
  - 1.8.5
    #  - 1.11.5
    #  - tip

os:
  - windows
    #  - linux
    #  - osx

dist: trusty
    
sudo: false

before_install:
- if [ ${TRAVIS_OS_NAME} == "windows" ]; then choco install make; fi        

before_script:
  - go get github.com/BurntSushi/toml
  - go get github.com/gershwinlabs/gokml       
  - go get github.com/stretchr/testify/assert
  - go vet ./...
