language: go

go:
  - 1.11.x
    #  - tip

os:
  - windows
  - linux
    #  - osx

dist: trusty
    
env:
  global:
  - DIST=US191/$TARGET/$TRAVIS_OS_NAME/
  - secure: Oe4tuCG+6IvilDR/NTos07eusDb5mBKfUGvhks61K9fBQdBKFdK+45npA8a8bAR65itl7oGHe/YT42GVOTvJfwqfGzM2YMIbYoa02az57bz/56iQjr75XnND6T7XljxYai1s6dGNG3oN1mmV1WSAawPQsRQ7XeZ5CiR2h7I/Rv2OxSoRLO37z/10c5ZcgkUVmHtqnGKctX7uXd7dg7pJ8wBg0yvYhqMawPRiNOVQcmCG8yPf5dmNOMyaHxbXNFSAj95tpag6UHbent+TQL/GD8XRWBqrkcOkSA4aPmjVVh4bF16aBDaEcVxodfN3ox5ASF/2fpydxUU/u3axBqiJ4C5VFIIBY8X56DsWhmXoXFhxyxqOtP0tVZmvvo1kIz2iOWPIo2HF8rkCMdIdrZ84PizzPCwOKFhw5l44yA9nAwGc9CM247kquBElumE5T0lpvA2f4f+HwHRCZZI/XYSJ64xdW1G8OKpjf3p1pDff8dLP6DFYHWMrMR2Pyemrg7q0x8tkNAes38IyhChVIl4MypLRx3MKOqygW1KzP51uruzS68AjndkgpGvOCfwtiIyc1RNC6vRDwjjBE1Keo76cWDM4D/PsCiJ91c8Y32g16GnoFo4LsFTpWQ04HZKH0T7GXGNrROVNalIF6QZgmhUeRvGLq8LYoVrlOqqiH0KTIXs=
  - secure: rmXDdTPQJLuJhS3WZ1f9rwgdJMjfSEtS2buk6Lt8DP50xJPcByEVCg2Lypopx+9CTfTEsFy6v2bTI2WT6b/5UGWuKTIHFRmwx74kLNbZE4m++XIVFqQAqiFjBHBLAPvf/2xBEGgyebkYW5uZSg83lG7lfB76fi3/RwdTr/88sdu6IfLi8DH6jlq5wmt88Hi2RO9qEb3rLA8ZZAH5v/z9mDJ+a86re78hCvOnPgG7I+kKAo2jB+UKnQP1MYgNcWskTyOYTzC90tcwVxtOtXNbZKHy9UJEQrazjY0Td+jvoDQW/Y7x9gZ1TYec8u61rqPt7/E7ak+Tp2wcagBlXT5cTyRrfoUI1SVwIej4TkCheIXJOeIkpUjUt8AR9zCR/r6vAavTdvdkc7BSNfguHIrzSR35gYuRgvHxRjHDBFkWVblrFm/5rjApj421kI833pnGJzQIMZxjyyLpYSXBOqcrCFYVkTdWXYbp6VlQ3AqcysW2K4uFHLb4z+p3ojjeJEShxHW/mT+n23DYFVBaBNMy7tdValoEoqjzju7UdMYZMrsh7R38faLvUKZfeyXXSG41NKBXh47Yg2I3sio9ItwizJavo4QRxQ3Ka5FAz+IaMRAjEyL6+dtEvqDGajg9NDgs9p9s+NlHbwVyY97mlf2S7+dARpu8ooMETszrVq5/jeg=

before_install:
- if [ ${TRAVIS_OS_NAME} == "windows" ]; then choco install make; fi        

before_script:
  - go get -t -v ./...    
  - go vet ./...

after_success:    
  - ls -la
  - curl -T $TARGET.exe --ftp-create-dirs ftp://$FTP_USER:$FTP_PASSWORD@ftp.ifremer.fr/${DIST}
  - curl -T config.toml ftp://$FTP_USER:$FTP_PASSWORD@ftp.ifremer.fr/${DIST}    
