# this is a configuration file for cruiseTrack2kml program

cruise = "AMOP"
ship = "ATALANTE"

ctd_plots = "C:/Users/jgrelet/go/src/github.com/jgrelet/cruiseTrack2kml/data/amop/ctd/dam%s.jpg"
tsg_plots = "C:/Users/jgrelet/go/src/github.com/jgrelet/cruiseTrack2kml/data/amop/tsg/AMOP-TSG-SST-SSPS-scatter.png"
#http:gcwww.brest.ird.fr/us191/cruises/cassiopee/CTD/plots/dcsp%s-TS02Dens.jpg'

[windows]
tsg_file = "C:/Users/jgrelet/go/src/github.com/jgrelet/cruiseTrack2kml/data/amop/amop.gps"
ctd_file = "C:/Users/jgrelet/go/src/github.com/jgrelet/cruiseTrack2kml/data/amop/amop.ctd"
kml_file = "C:/Users/jgrelet/go/src/github.com/jgrelet/cruiseTrack2kml/amop.kml"

[unix]
tsg_file = "./data/amop/amop.gps"
ctd_file = "./data/amop/amop.ctd"
kml_file = "./amop.kml"
