# this is a configuration file for cruiseTrack2kml program

cruise = "AMOP"
ship = "ATALANTE"

ctdPlots = "data/amop/ctd/dam%s.jpg"
ctdPrefix = 5
tsgPlots = "data/amop/tsg/AMOP-TSG-SST-SSPS-scatter.png"
sizePlots = 700
stationNumber = true

[windows]
tsgFile = "data/amop/amop.gps"
ctdFile = "data/amop/amop.ctd"
kmlFile = "amop.kml"

[unix]
tsgFile = "./data/amop/amop.gps"
ctdFile = "./data/amop/amop.ctd"
kmlFile = "./amop.kml"
