# this is a configuration file for cruiseTrack2kml program

cruise = "AMOP"
ship = "ATALANTE"

ctd_plots = "data/amop/ctd/dam%s.jpg"
ctd_prefix = 5
tsg_plots = "data/amop/tsg/AMOP-TSG-SST-SSPS-scatter.png"
size_plots = 700
station_number = true

[windows]
tsg_file = "data/amop/amop.gps"
ctd_file = "data/amop/amop.ctd"
kml_file = "amop.kml"

[unix]
tsg_file = "./data/amop/amop.gps"
ctd_file = "./data/amop/amop.ctd"
kml_file = "./amop.kml"
