# this is a configuration file for cruiseTrack2kml program

cruise = "AMAZOMIX"
ship = "ANTEA"
sizePlots = 700
stationNumber = true
file = "netcdf"
time = 'TIME'
latitude = 'LATITUDE'
longitude = 'LONGITUDE'
profile = 'PROFILE'

# File is relative from Drive
[ctd]
file = 'data/amazomix/OS_AMAZOMIX_CTD.nc'
name = 'St'
plots = "http://www.brest.ird.fr/us191/cruises/amazomix/CTD/AMAZOMIX-{:05d}_CTD.png"

[xbt]
#file = "none"
file = 'data/amazomix/OS_AMAZOMIX_XBT.nc'
name = 'Xbt'
plots = "http://www.brest.ird.fr/us191/cruises/amazomix/XBT/AMAZOMIX-{:05d}_XBT.png"

[tsg]
file = "data/amazomix/OS_AMAZOMIX_TSG.nc"
params = 'SSPS,SSTP'
plots = "http://www.brest.ird.fr/us191/cruises/amazomix/TSG/AMAZOMIX_TSG_COLCOR_SCATTER.png"

[windows]
drive = "m:"

[unix]
drive = "/m"
