# this is a configuration file for cruiseTrack2kml program

cruise = "ABRACOS2"
ship = "ANTEA"

ctdPlots = "http://192.168.81.172/ABRA2-CTD/dabra2%s.jpg"
ctdPrefix = 3
tsgPlots = "http://192.168.81.172/ABRA2-TSG/ABRACOS2_TSG_COLCOR_SQUATTER.png"

sizePlots = 700
stationNumber = true
tsgSkip = 0
tsgSplit = "LATITUDE,2,float64,LONGITUDE,3,float64"
#tsgSkip = 2
#tsgSplit = "LATITUDE,3,LONGITUDE,4"
ctdSkip = 1
ctdSplit = "PRFL,1,int,BEGIN_DATE,2,string,BEGIN_TIME,3,string,END_DATE,4,string,END_TIME,5,string,LAT,6,string,LAT_S,7,string,LON,8,string,LON_S,9,string,PMAX,10,float64,BOTTOM_DEPTH,11,float64"

[windows]
tsgFile = "M:/ABRACOS2/data-processing/THERMO/ascii/abracos2-raw.gps"
#tsgFile = "data/abracos2/abracos2-raw.gps"
ctdFile = "M:/ABRACOS2/data-processing/CTD/ascii/abracos2.ctd"
#ctdFile = "data/abracos2/abracos2.ctd"
kmlFile = "abracos2.kml"

[unix]
tsgFile = "./data/fr26/ascii/pirata-fr26.gps"
ctdFile = "./data/fr26/pirata-fr26.ctd"
kmlFile = "./pirata-fr26.kml"
