# this is a configuration file for cruiseTrack2kml program

cruise = "PIRATA-FR31"
ship = "THALASSA"
sizePlots = 700
stationNumber = true
file = "netcdf"
time = 'TIME'
latitude = 'LATITUDE'
longitude = 'LONGITUDE'
profile = 'PROFILE'

# File is relative from Drive
[ctd]
file = 'data/fr31/OS_PIRATA-FR31_CTD.nc'
name = 'St'
nameFormat = 3
plots = "http://www.brest.ird.fr/us191/cruises/pirata-fr31/CTD/PIRATA-FR31-{:03d}_CTD.png"

[xbt]
#file = "none"
file = 'data/fr31/OS_PIRATA-FR31_XBT.nc'
name = 'Xbt'
nameFormat = 3
plots = "http://www.brest.ird.fr/us191/cruises/pirata-fr31/XBT/PIRATA-FR31-{:03d}_XBT.png"

[tsg]
file = "data/fr31/OS_PIRATA-FR31_TSG.nc"
params = 'SSPS,SSTP'
plots = "http://www.brest.ird.fr/us191/cruises/pirata-fr31/TSG/PIRATA-FR31_TSG_COLCOR_SCATTER.png"

[tao]
# https://www.pmel.noaa.gov/tao/drupal/pirata-display/gif/buoy_0n10w.gif

[windows]
drive = "m:"

[unix]
drive = "/m"
